# Generated by Django 4.0.3 on 2022-04-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
