# Generated by Django 4.0.3 on 2022-04-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_date_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
